# Generated by Django 4.2.5 on 2023-10-18 06:45


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('maps', models.TextField()),
                ('tentang', models.TextField()),
                ('tentang_footer', models.TextField()),
                ('kontak', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'about',
            },
        ),
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('tanggal', models.TimeField()),
                ('artikel', models.TextField()),
                ('img', models.CharField(max_length=50)),
                ('validasi_id', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=50)),
                ('petugas_id', models.CharField(max_length=50)),
                ('validator', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'artikel',
            },
        ),
        migrations.CreateModel(
            name='Diagnosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosa', models.CharField(max_length=20)),
                ('gejala', models.TextField(null=True)),
                ('pengecekan_luar', models.TextField(null=True)),
                ('pengecekan_dalam', models.TextField(null=True)),
                ('penanganan', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'diagnosa',
            },
        ),
        migrations.CreateModel(
            name='LaporanKegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('tanggal', models.TimeField()),
                ('kegiatan', models.TextField()),
                ('img', models.CharField(max_length=50)),
                ('validasi_id', models.CharField(max_length=50, null=True)),
                ('info', models.CharField(max_length=50, null=True)),
                ('petugas_id', models.CharField(max_length=50, null=True)),
                ('validator', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'laporan_kegiatan',
            },
        ),
        migrations.CreateModel(
            name='LaporanSdp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('jenis', models.CharField(max_length=50)),
                ('masuk', models.CharField(max_length=50)),
                ('keluar', models.CharField(max_length=50)),
                ('tanggal', models.TimeField()),
                ('validasi_id', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=50)),
                ('petugas_id', models.CharField(max_length=50)),
                ('validator_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'laporan_sdp',
            },
        ),
        migrations.CreateModel(
            name='JenisSdp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('fungsi', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jenis_sdp',
            },
        ),
        migrations.CreateModel(
            name='MenuDiagnosaPenanganan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField(null=True)),
                ('inisial', models.TextField(null=True)),
                ('link', models.TextField()),
                ('link_view', models.TextField(null=True)),
                ('level', models.CharField(max_length=30)),
                ('is_staff', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'menu_diagnosa_penanganan',
            },
        ),
        migrations.CreateModel(
            name='MenuGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField()),
                ('link', models.TextField()),
                ('level', models.CharField(max_length=3, null=True)),
            ],
            options={
                'db_table': 'menu_general',
            },
        ),
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('tanggal', models.TimeField()),
                ('pengumuman', models.TextField()),
                ('petugas_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pengumuman',
            },
        ),
        migrations.CreateModel(
            name='Pakar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umur', models.CharField(max_length=20, null=True)),
                ('gejala', models.TextField(null=True)),
                ('pengecekan_luar', models.TextField(null=True)),
                ('pengecekan_dalam', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('diagnosa', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='apps.diagnosa')),
            ],
            options={
                'db_table': 'data_pakar',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField()),
                ('link', models.TextField()),
                ('icon', models.CharField(max_length=40)),
                ('groups', models.ManyToManyField(blank=True, related_name='menus', to='auth.group')),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='DataSuspek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_ktp', models.CharField(max_length=16, null=True)),
                ('nama', models.TextField()),
                ('alamat', models.TextField()),
                ('gejala_luar', models.TextField(null=True)),
                ('gejala_dalam', models.TextField(null=True)),
                ('penanganan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(auto_now=True, null=True)),
                ('diagnosa', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.diagnosa')),
                ('petugas', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_suspek',
            },
        ),
    ]
