# Generated by Django 5.0.3 on 2024-05-02 11:21

import apps.base.posbindu.models.informasi.m_artikel
import apps.base.posbindu.models.laporan.m_laporan_kegiatan
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat', models.TextField()),
                ('umur', models.CharField(max_length=3, null=True)),
                ('hasil', models.CharField(max_length=10, null=True)),
                ('total', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'dashboard',
            },
        ),
        migrations.CreateModel(
            name='DataSdp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('kode', models.CharField(max_length=50, null=True)),
                ('jumlah_masuk', models.CharField(max_length=50, null=True)),
                ('jumlah_keluar', models.CharField(max_length=50, null=True)),
                ('Total', models.CharField(max_length=50, null=True)),
                ('satuan', models.CharField(max_length=50, null=True)),
                ('kadaluarsa', models.CharField(max_length=50, null=True)),
                ('produk', models.CharField(max_length=50, null=True)),
                ('info', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'data_sdp',
            },
        ),
        migrations.CreateModel(
            name='Gejala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField(null=True)),
                ('alias', models.TextField(null=True)),
                ('jenis', models.TextField(null=True)),
                ('pernyataan', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gejala',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'gender',
            },
        ),
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, null=True)),
                ('kriteria', models.TextField(null=True)),
                ('badge', models.CharField(max_length=50, null=True)),
                ('apper', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'kriteria',
            },
        ),
        migrations.CreateModel(
            name='Validasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'validasi',
            },
        ),
        migrations.RenameModel(
            old_name='MenuGeneral',
            new_name='MenuHome',
        ),
        migrations.DeleteModel(
            name='JenisSdp',
        ),
        migrations.RenameField(
            model_name='datasuspek',
            old_name='gejala_dalam',
            new_name='data_dalam',
        ),
        migrations.RenameField(
            model_name='datasuspek',
            old_name='gejala_luar',
            new_name='data_gejala',
        ),
        migrations.RenameField(
            model_name='diagnosa',
            old_name='gejala',
            new_name='data_dalam',
        ),
        migrations.RenameField(
            model_name='diagnosa',
            old_name='pengecekan_dalam',
            new_name='data_gejala',
        ),
        migrations.RenameField(
            model_name='diagnosa',
            old_name='pengecekan_luar',
            new_name='data_khusus',
        ),
        migrations.RenameField(
            model_name='laporankegiatan',
            old_name='petugas_id',
            new_name='upload',
        ),
        migrations.RenameField(
            model_name='pakar',
            old_name='gejala',
            new_name='data_dalam',
        ),
        migrations.RenameField(
            model_name='pakar',
            old_name='pengecekan_dalam',
            new_name='data_gejala',
        ),
        migrations.RenameField(
            model_name='pakar',
            old_name='pengecekan_luar',
            new_name='data_khusus',
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='petugas_id',
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='validasi_id',
        ),
        migrations.RemoveField(
            model_name='laporankegiatan',
            name='validasi_id',
        ),
        migrations.RemoveField(
            model_name='laporansdp',
            name='petugas_id',
        ),
        migrations.RemoveField(
            model_name='laporansdp',
            name='validasi_id',
        ),
        migrations.RemoveField(
            model_name='laporansdp',
            name='validator_id',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='pengumuman',
            name='petugas_id',
        ),
        migrations.AddField(
            model_name='artikel',
            name='petugas',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artikel_petugas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artikel',
            name='upload',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datasuspek',
            name='data_khusus',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datasuspek',
            name='data_luar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datasuspek',
            name='pelaksanaan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datasuspek',
            name='umur',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='diagnosa',
            name='data_luar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='laporankegiatan',
            name='petugas',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laporankegiatan_petugas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laporansdp',
            name='bukti',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='laporansdp',
            name='kadaluarsa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laporansdp',
            name='keperluan',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='laporansdp',
            name='kode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laporansdp',
            name='petugas',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laporansdp_petugas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laporansdp',
            name='upload',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='laporansdp',
            name='validasi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='laporansdp',
            name='validator',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laporansdp_validator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menu',
            name='group',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='pakar',
            name='data_luar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pengumuman',
            name='petugas',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='delete_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='img',
            field=models.ImageField(null=True, upload_to=apps.base.posbindu.models.informasi.m_artikel.upload_path_img),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='info',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='judul',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='tanggal',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='validator',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artikel_validator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datasuspek',
            name='penanganan',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='laporankegiatan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='laporankegiatan',
            name='delete_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='laporankegiatan',
            name='img',
            field=models.ImageField(null=True, upload_to=apps.base.posbindu.models.laporan.m_laporan_kegiatan.upload_path_img),
        ),
        migrations.AlterField(
            model_name='laporankegiatan',
            name='tanggal',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='laporankegiatan',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='laporankegiatan',
            name='validator',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laporankegiatan_validator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='laporansdp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='laporansdp',
            name='delete_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='laporansdp',
            name='tanggal',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='laporansdp',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='pakar',
            name='diagnosa',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.diagnosa'),
        ),
        migrations.AlterField(
            model_name='pengumuman',
            name='tanggal',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='diagnosa',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.diagnosa'),
        ),
        migrations.AlterField(
            model_name='laporansdp',
            name='jenis',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.datasdp'),
        ),
        migrations.AddField(
            model_name='gejala',
            name='rule',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='apps.diagnosa'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='gender',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.gender'),
        ),
        migrations.AddField(
            model_name='datasuspek',
            name='gender',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.gender'),
        ),
        migrations.AddField(
            model_name='datasdp',
            name='kondisi',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.kriteria'),
        ),
        migrations.AddField(
            model_name='laporansdp',
            name='kondisi',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.kriteria'),
        ),
        migrations.AddField(
            model_name='artikel',
            name='validasi',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validasi', to='apps.validasi'),
        ),
        migrations.AddField(
            model_name='laporankegiatan',
            name='validasi',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.validasi'),
        ),
    ]
