# Generated by Django 5.0.3 on 2024-05-06 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_dashboard_datasdp_gejala_gender_kriteria_validasi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menudiagnosapenanganan',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='menudiagnosapenanganan',
            name='level',
        ),
        migrations.RemoveField(
            model_name='menudiagnosapenanganan',
            name='link_view',
        ),
    ]
