# Generated by Django 5.0.3 on 2024-05-06 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_remove_menudiagnosapenanganan_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuDiagnosaPenanganan',
            new_name='MenuDiagnosis',
        ),
        migrations.AlterModelTable(
            name='menudiagnosis',
            table='menu_diagnosis',
        ),
    ]
