# Generated by Django 5.0.3 on 2024-05-07 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_rename_menudiagnosapenanganan_menudiagnosis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kondisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, null=True)),
                ('badge', models.CharField(max_length=50, null=True)),
                ('apper', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'kondisi',
            },
        ),
        migrations.AlterField(
            model_name='datasdp',
            name='kondisi',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.kondisi'),
        ),
        migrations.AlterField(
            model_name='laporansdp',
            name='kondisi',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.kondisi'),
        ),
        migrations.DeleteModel(
            name='Kriteria',
        ),
    ]
