# Generated by Django 5.0.3 on 2024-05-07 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_kondisi_alter_datasdp_kondisi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kondisi',
            name='apper',
        ),
    ]
