# Generated by Django 5.0.3 on 2024-05-07 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_remove_kondisi_apper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kondisi',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='kondisi',
            name='update_at',
        ),
    ]
