# Generated by Django 5.0.3 on 2024-05-07 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_remove_kondisi_created_at_remove_kondisi_update_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasdp',
            old_name='Total',
            new_name='total',
        ),
    ]
