# Generated by Django 5.0.3 on 2024-05-07 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_rename_total_datasdp_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gejala',
            name='rule',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.diagnosa'),
        ),
    ]
