# Generated by Django 5.0.3 on 2024-05-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_alter_gejala_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengumuman',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pengumuman',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
