# Generated by Django 5.0.3 on 2024-05-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_alter_pengumuman_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengumuman',
            name='waktu',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
