# Generated by Django 5.0.3 on 2024-05-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_pengumuman_waktu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengumuman',
            name='waktu',
            field=models.CharField(max_length=50),
        ),
    ]
