# Generated by Django 5.0.3 on 2024-05-08 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_alter_pengumuman_waktu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasuspek',
            old_name='pelaksanaan',
            new_name='tanggal',
        ),
    ]
