# Generated by Django 5.0.3 on 2024-05-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_rename_pelaksanaan_datasuspek_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='gejala',
            name='penanganan',
            field=models.TextField(null=True),
        ),
    ]
