# Generated by Django 5.0.3 on 2024-05-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_gejala_penanganan'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipePenyakit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.TextField(null=True)),
                ('nama', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipe_penyakit',
            },
        ),
    ]
