# Generated by Django 5.0.3 on 2024-05-18 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_tipepenyakit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosa',
            name='diagnosa',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.tipepenyakit'),
        ),
    ]
