# Generated by Django 5.0.3 on 2024-05-18 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_diagnosa_kode_alter_diagnosa_diagnosa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosa',
            name='kode',
        ),
    ]
