# Generated by Django 5.0.3 on 2024-05-18 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_diagnosa_tipe_alter_diagnosa_kode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosa',
            name='kode',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='diagnosa',
            name='tipe',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='apps.tipepenyakit'),
        ),
    ]
