# Generated by Django 5.0.6 on 2024-05-31 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_alter_diagnosa_kode_alter_diagnosa_tipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pakar',
            name='data_dalam',
        ),
        migrations.RemoveField(
            model_name='pakar',
            name='data_luar',
        ),
    ]
