# Generated by Django 5.0.6 on 2024-06-04 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_notificationtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationType',
        ),
    ]
