# Generated by Django 5.0.6 on 2024-06-04 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0025_notifikasi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifikasi',
            name='petugas',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi_petugas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notifikasi',
            name='validator',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi_validator', to=settings.AUTH_USER_MODEL),
        ),
    ]
