# Generated by Django 5.0.6 on 2024-06-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0026_alter_notifikasi_petugas_alter_notifikasi_validator'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Notifikasi',
        ),
    ]
