# Generated by Django 5.0.6 on 2024-06-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0029_remove_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitur', models.CharField(max_length=50)),
                ('verb', models.CharField(max_length=50)),
                ('kegiatan', models.TextField()),
                ('petugas', models.CharField(max_length=50, null=True)),
                ('validator', models.CharField(max_length=50, null=True)),
                ('is_read', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'notifikasi',
            },
        ),
    ]
