# Generated by Django 5.0.6 on 2024-06-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0030_notifikasi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifikasi',
            old_name='delete_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='notifikasi',
            name='update_at',
        ),
        migrations.AddField(
            model_name='notifikasi',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notifikasi',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notifikasi',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
