# Generated by Django 5.0.6 on 2024-06-05 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0031_rename_delete_at_notifikasi_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifikasi',
            name='kegiatan',
        ),
    ]
