# Generated by Django 5.0.6 on 2024-06-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0032_remove_notifikasi_kegiatan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='kontak',
            new_name='sosmed',
        ),
        migrations.RemoveField(
            model_name='about',
            name='update_at',
        ),
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='telp',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
