# Generated by Django 5.0.6 on 2024-06-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0034_rename_delete_at_artikel_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengumuman',
            name='tempat',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
