# Generated by Django 5.0.6 on 2024-06-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0035_pengumuman_tempat'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='alamat',
            field=models.TextField(null=True),
        ),
    ]
