# Generated by Django 5.0.6 on 2024-06-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0037_alter_laporansdp_validasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengumuman',
            name='jenis',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
