# Generated by Django 5.0.6 on 2024-07-01 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0038_pengumuman_jenis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasuspek',
            old_name='no_ktp',
            new_name='nik',
        ),
    ]
