# Generated by Django 5.0.6 on 2024-07-02 07:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0039_rename_no_ktp_datasuspek_nik'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifikasi',
            old_name='is_read',
            new_name='is_deleted',
        ),
        migrations.AddField(
            model_name='notifikasi',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, related_name='delete_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notifikasi',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
