# Generated by Django 5.0.6 on 2024-07-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0040_rename_is_read_notifikasi_is_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifikasi',
            old_name='petugas',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='notifikasi',
            name='validator',
        ),
        migrations.AddField(
            model_name='notifikasi',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
