# Generated by Django 5.0.6 on 2024-07-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0041_rename_petugas_notifikasi_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifikasi',
            name='url',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
