# Generated by Django 5.0.6 on 2024-07-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0042_notifikasi_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifikasi',
            name='nama',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
