# Generated by Django 5.0.6 on 2024-07-17 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0043_notifikasi_nama'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notifikasi',
            table='notifikasi_njajal',
        ),
    ]
