# Generated by Django 5.0.6 on 2024-07-17 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0044_alter_notifikasi_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notifikasi',
            table='notifikasi',
        ),
    ]
