# Generated by Django 5.0.6 on 2024-07-18 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0045_alter_notifikasi_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pakar',
            table='inference_engine',
        ),
        migrations.CreateModel(
            name='Kepakaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umur', models.CharField(max_length=20, null=True)),
                ('data_gejala', models.TextField(null=True)),
                ('data_khusus', models.TextField(null=True)),
                ('alasan', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('diagnosa', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.diagnosa')),
            ],
            options={
                'db_table': 'knowledge_acquisition',
            },
        ),
    ]
