# Generated by Django 5.0.6 on 2024-07-19 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0047_tipepengumuman'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipePengumuman',
        ),
    ]
