# Generated by Django 5.0.6 on 2024-07-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0048_delete_tipepengumuman'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipePengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'tipe_pengumuman',
            },
        ),
    ]
