# Generated by Django 5.0.6 on 2024-07-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0049_tipepengumuman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengumuman',
            name='jenis',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='tipepengumuman',
            table='tipepengumuman',
        ),
    ]
