# Generated by Django 5.0.6 on 2024-07-27 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0050_alter_pengumuman_jenis_alter_tipepengumuman_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kepakaran',
            old_name='diagnosa',
            new_name='diagnosa_sistem',
        ),
        migrations.AddField(
            model_name='kepakaran',
            name='diagnosa_suspek',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.diagnosa'),
        ),
    ]
