# Generated by Django 5.0.6 on 2024-07-27 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0051_rename_diagnosa_kepakaran_diagnosa_sistem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kepakaran',
            name='diagnosa_sistem',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kepakaran_sistem', to='apps.diagnosa'),
        ),
        migrations.AlterField(
            model_name='kepakaran',
            name='diagnosa_suspek',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kepakaran_suspek', to='apps.diagnosa'),
        ),
    ]
