# Generated by Django 5.0.7 on 2024-08-18 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0052_alter_kepakaran_diagnosa_sistem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gejala',
            name='rule',
        ),
    ]
