# Generated by Django 5.0.7 on 2024-08-18 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0053_remove_gejala_rule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laporankegiatan',
            old_name='img',
            new_name='foto',
        ),
    ]
