# Generated by Django 5.0.7 on 2024-08-18 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0054_rename_img_laporankegiatan_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikel',
            old_name='img',
            new_name='gambar',
        ),
    ]
