# Generated by Django 5.0.7 on 2024-08-19 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0055_rename_img_artikel_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengumuman',
            name='jenis',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.tipepengumuman'),
        ),
    ]
