# Generated by Django 5.0.7 on 2024-08-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0057_alter_datasuspek_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasuspek',
            name='tanggal',
            field=models.CharField(max_length=50),
        ),
    ]
