# Generated by Django 5.0.7 on 2024-08-19 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0058_alter_datasuspek_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasuspek',
            name='tanggal',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.pengumuman'),
        ),
    ]
