# Generated by Django 5.0.7 on 2024-10-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0060_alter_datasuspek_tanggal'),
    ]

    operations = [
        migrations.CreateModel(
            name='WilayahKerja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wilayah_kerja', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'wilayah_kerja',
            },
        ),
    ]
