# Generated by Django 5.0.7 on 2024-10-02 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0061_wilayahkerja'),
    ]

    operations = [
        migrations.AddField(
            model_name='wilayahkerja',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 2, 8, 59, 59, 427579, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wilayahkerja',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wilayahkerja',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='notifikasi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
