# Generated by Django 5.0.7 on 2024-10-02 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0062_wilayahkerja_created_at_wilayahkerja_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Satuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wilayah_kerja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.wilayahkerja')),
            ],
        ),
    ]
