# Generated by Django 5.0.7 on 2024-10-02 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0063_satuan'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='satuan',
            table='satuan',
        ),
    ]
