# Generated by Django 5.0.7 on 2024-10-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0064_alter_satuan_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='judul',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
