# Generated by Django 5.0.7 on 2024-10-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0067_alter_artikel_gambar_alter_laporankegiatan_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporansdp',
            name='kode',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
