# Generated by Django 5.0.7 on 2024-10-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0068_alter_laporansdp_kode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporansdp',
            name='kode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
