# Generated by Django 5.0.7 on 2024-10-15 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0071_alter_laporansdp_kondisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporansdp',
            name='kondisi',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.kondisi'),
        ),
    ]
