# Generated by Django 5.0.7 on 2024-10-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0072_alter_laporansdp_kondisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='alias',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
