# Generated by Django 5.0.7 on 2024-12-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0073_gender_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPenyakit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'status_penyakit',
            },
        ),
    ]
