# Generated by Django 5.0.7 on 2024-12-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0074_statuspenyakit'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosa',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
