# Generated by Django 5.0.7 on 2024-12-17 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0075_diagnosa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosa',
            name='status',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='apps.statuspenyakit'),
        ),
    ]
