# Generated by Django 5.0.7 on 2024-12-17 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0078_rename_status_diagnosa_status_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosa',
            old_name='status_id',
            new_name='status',
        ),
    ]
